"""
State Transfer Descriptor.

Describes what state needs to be transferred from prefill to decode GPU.
Handles two heterogeneous state types:
  - Full attention KV Cache (block-granularity, quantizable)
  - Linear attention recurrent states (whole, FP32, not quantizable)
"""

from dataclasses import dataclass, field
from typing import List, Optional, Tuple
from enum import Enum


class RegionType(str, Enum):
    """Type of state region to transfer."""
    FULL_ATTN_KV = "full_attn_kv"
    LINEAR_SSM = "linear_ssm"
    LINEAR_CONV = "linear_conv"


@dataclass
class RegionDescriptor:
    """
    Describes a region of state to transfer.

    Each region is a contiguous chunk of state data with a specific type,
    layer range, and dtype. The transfer layer uses this to determine
    whether quantization applies and how to serialize.
    """
    region_type: RegionType
    layer_indices: List[int]           # Which layers this region covers
    shape: Tuple[int, ...]             # Tensor shape
    dtype: str                         # "bfloat16" | "int4" | "float32"
    quantized: bool = False            # Whether this region uses INT4 compression
    src_gpu: int = 0                   # Source GPU ID
    dst_gpu: int = 1                   # Destination GPU ID
    size_bytes: int = 0                # Computed size in bytes

    def __post_init__(self):
        if self.size_bytes == 0:
            dtype_sizes = {"bfloat16": 2, "float16": 2, "float32": 4, "int4": 0.5}
            elem_size = dtype_sizes.get(self.dtype, 2)
            total_elems = 1
            for d in self.shape:
                total_elems *= d
            self.size_bytes = int(total_elems * elem_size)

    @property
    def size_mb(self) -> float:
        return self.size_bytes / (1024 * 1024)


@dataclass
class StateTransferDescriptor:
    """
    Complete description of state to transfer for a single request.

    Generated by the prefill engine after prefill completes.
    Consumed by the transfer pipeline and decode engine.

    Includes first-token seeding optimization: if the prefill engine
    already sampled the first token, it's included in the descriptor
    to save ~58ms decode-side recomputation.
    """
    request_id: int
    model_name: str
    first_token_id: Optional[int] = None   # First-token seeding
    first_token_logprob: Optional[float] = None
    regions: List[RegionDescriptor] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    @property
    def total_size_mb(self) -> float:
        return sum(r.size_mb for r in self.regions)

    @property
    def total_size_bytes(self) -> int:
        return sum(r.size_bytes for r in self.regions)

    @property
    def has_kv_cache(self) -> bool:
        return any(r.region_type == RegionType.FULL_ATTN_KV for r in self.regions)

    @property
    def has_recurrent_state(self) -> bool:
        return any(r.region_type in (RegionType.LINEAR_SSM, RegionType.LINEAR_CONV)
                   for r in self.regions)

    def get_regions_by_type(self, region_type: RegionType) -> List[RegionDescriptor]:
        return [r for r in self.regions if r.region_type == region_type]

    def estimate_transfer_time_ms(self, bandwidth_gb_s: float) -> float:
        """Estimate transfer time at given bandwidth."""
        return (self.total_size_bytes / (bandwidth_gb_s * 1e9)) * 1000

    def to_metadata_dict(self) -> dict:
        """Convert to dict for IPC/wire format."""
        return {
            "request_id": self.request_id,
            "model_name": self.model_name,
            "first_token_id": self.first_token_id,
            "first_token_logprob": self.first_token_logprob,
            "total_size_mb": self.total_size_mb,
            "num_regions": len(self.regions),
            "region_types": [r.region_type.value for r in self.regions],
            "metadata": self.metadata,
        }
